language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install

script:
  - ./vendor/bin/phpunit;

jobs:
  include:
    - stage: Test
      name: Lowest dependencies
      php: 7.2
      install: composer install --prefer-dist --prefer-lowest

    - stage: Test
      name: Code coverage
      php: 7.2
      before_script:
      script:
        - ./vendor/bin/phpunit --coverage-clover=coverage.clover
